#!/usr/bin/env python3
"""
Offline generator for the fixedpoint-fft quarter-wave cosine tables.

This script is a *build-time host tool* - it is never compiled into the
Arduino sketch and never runs on the target. Its only job is to produce
the flash-resident lookup tables in src/fixedpoint_fft/generated/, so
that the library itself never has to call sin()/cos() (or any other
trigonometric function) at runtime.

Usage:
    python3 tools/generate_twiddles.py [--max-n 4096] [--out-dir src/fixedpoint_fft/generated]

Only powers of two are accepted for --max-n. The generated tables cover
one quarter period (0 .. pi/2 inclusive), i.e. max_n/4 + 1 entries. The
library reconstructs the full circle via quadrant folding at runtime
(see Twiddles.h), and can run any power-of-two FFT length from 2 up to
max_n using a single set of tables (indexed with a stride).

Re-run this script (with a larger --max-n) if you need to support
bigger FFT sizes than the checked-in default supports; it will
overwrite the generated headers in place.
"""
import argparse
import math
import os
import datetime

# (suffix, fractional_bits, c_type) - fractional_bits=None means a plain
# floating point table (values stored as literal cos()/sin() results, no
# Qn quantization/scaling/clamping): used for the optional `float`/
# `double` calc types. `float` is fastest on MCUs with a hardware
# single-precision FPU (e.g. ESP32/ESP32-S3, ARM Cortex-M4F/M7); `double`
# is a desktop-only precision option (see FixedFFTEngine.h) - real MCU
# targets either emulate it in software or get no benefit over float.
TYPES = [
    ("q7", 7, "int8_t"),
    ("q15", 15, "int16_t"),
    ("q31", 31, "int32_t"),
    ("f32", None, "float"),
    ("f64", None, "double"),
]

# C++ literal suffix and decimal digits (enough to round-trip exactly)
# per floating point c_type.
FLOAT_LITERAL_SUFFIX = {"float": "f", "double": ""}
FLOAT_LITERAL_DIGITS = {"float": 9, "double": 17}
SIZE_BYTES = {"int8_t": 1, "int16_t": 2, "int32_t": 4, "float": 4, "double": 8}


def is_pow2(n: int) -> bool:
    return n > 0 and (n & (n - 1)) == 0


def generate_table(max_n: int, frac_bits):
    """Return list of max_n/4 + 1 cos(2*pi*i/max_n) values: quantized to
    Qn integers when frac_bits is set, or plain floats when it's None."""
    quarter = max_n // 4
    if frac_bits is None:
        return [math.cos(2.0 * math.pi * i / max_n) for i in range(quarter + 1)]

    scale = (1 << frac_bits) - 1  # largest representable positive Qn value
    table = []
    for i in range(quarter + 1):
        angle = 2.0 * math.pi * i / max_n
        val = round(math.cos(angle) * scale)
        if val > scale:
            val = scale
        if val < -(scale + 1):
            val = -(scale + 1)
        table.append(val)
    return table


def format_value(v, frac_bits, c_type) -> str:
    if frac_bits is None:
        # Fixed notation (not %g) so there's always a decimal point -
        # "1f" isn't a valid C++ float literal, "1.000000000f" is.
        digits = FLOAT_LITERAL_DIGITS[c_type]
        suffix = FLOAT_LITERAL_SUFFIX[c_type]
        return f"{v:.{digits}f}{suffix}"
    return str(v)


def emit_header(path: str, suffix: str, c_type: str, frac_bits, max_n: int, table):
    quarter = max_n // 4
    lines = []
    lines.append(f"// Auto-generated by tools/generate_twiddles.py - do not edit by hand.")
    lines.append(f"// Generated: {datetime.datetime.now(datetime.timezone.utc).isoformat()}")
    lines.append(f"// max_n={max_n} frac_bits={frac_bits} type={c_type}")
    lines.append(f"#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("namespace fixedpoint_fft {")
    lines.append("")
    lines.append(f"static constexpr uint16_t kTwiddle{suffix.upper()}MaxN = {max_n};")
    lines.append(f"static constexpr uint16_t kTwiddle{suffix.upper()}QuarterLen = {quarter + 1};")
    lines.append("")
    lines.append(f"FFT_TABLE_ATTR static const {c_type} kTwiddle{suffix.upper()}Quarter[{quarter + 1}] = {{")
    row = []
    for i, v in enumerate(table):
        row.append(format_value(v, frac_bits, c_type))
        if len(row) == 12:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace fixedpoint_fft")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-n", type=int, default=4096,
                     help="Maximum FFT length the tables must support (power of two, default 4096)")
    ap.add_argument("--out-dir", type=str,
                     default=os.path.join(os.path.dirname(__file__), "..", "src", "fixedpoint_fft", "generated"))
    args = ap.parse_args()

    if not is_pow2(args.max_n) or args.max_n < 4:
        raise SystemExit("--max-n must be a power of two >= 4")

    out_dir = os.path.abspath(args.out_dir)
    os.makedirs(out_dir, exist_ok=True)

    for suffix, frac_bits, c_type in TYPES:
        table = generate_table(args.max_n, frac_bits)
        out_path = os.path.join(out_dir, f"twiddles_{suffix}.h")
        emit_header(out_path, suffix, c_type, frac_bits, args.max_n, table)
        size_bytes = len(table) * SIZE_BYTES[c_type]
        print(f"wrote {out_path} ({len(table)} entries, ~{size_bytes} bytes)")


if __name__ == "__main__":
    main()
